homework: blog&form with CSS
tSpiny/purpleschool-html-css pull request #2
Opened 2024-05-13 12:55 UTC by tSpiny

- 1-blog modified according to tasks (9.9, 12.8)
- 2-form modified according to task (7.9)

2024-05-13 13:19 UTC, GitEsense requested changes
Всё окей в принципе, но можно оптимизировать, так же нужно ещё добавить "размеры блоков" и отцентровать. Примеры уже есть в комментариях.

а вот проект "2-form" не достилизован - над ним надо ещё поработать

2024-05-13 13:19 UTC, GitEsense commented on 1-blog/styles/style.css
> +}
а как насчёт убрать margin по умолчанию? ведь в useragent'е margin = 8px

2024-05-13 13:19 UTC, GitEsense commented on 1-blog/index.html
> +          <p class="meta">FRONTEND &sdot; <time>12 мая 2024</time></p>
`&sdot;` вовсе не оно, там `&bull;`

2024-05-13 13:19 UTC, GitEsense commented on 1-blog/index.html
> +      <div><a href="#" class="hero-link">Мой блог</a></div>
а иконку `В` потеряли

2024-05-13 13:19 UTC, GitEsense commented on 1-blog/index.html
> +          <p class="first">
На самом деле все эти три параграфа можно было бы положить в один div, что-то вроде
```html
<div class="content">
   <p>...</p>
   <p>...</p>
   <p>...</p>
</div>
```
а в CSS уже сделать
```css
body {
    color: #FFFFFF;
    background: linear-gradient(180deg, #374151 0%, #111827 82.6%, #121928 100%); 
    font-family: Roboto;
    font-weight: 400;
    font-size: 16px; /* тогда весь документ по умолчанию будет получать шрифт 16px, если не указано иное */
    margin: 0;
} 

p {
   margin: 0;
}
.content {
    max-width: 708px; /* ограничиваем размер блока */
    margin: 0 auto; /* left and right = auto, top and bottom = 0, тем самым выставляем по центру */
}
.content p {
   margin-bottom: 38px;
   line-height: 30px;
}

.content p:first-child {
    font-size: 20px;
    line-height: 32px;
} 
.content p:last-child {
   margin-bottom: unset;
}
```

2024-05-13 14:10 UTC, tSpiny commented on 1-blog/index.html
> +          <p class="meta">FRONTEND &sdot; <time>12 мая 2024</time></p>
исправлено)

2024-05-13 14:10 UTC, tSpiny commented on 1-blog/index.html
> +      <div><a href="#" class="hero-link">Мой блог</a></div>
иконку добавила отдельным div

2024-05-13 14:12 UTC, tSpiny commented on 1-blog/index.html
> +          <p class="first">
Так выглядит лучше, переписала, правда с выравниванием через auto не оч понятно - это работает для всех блочных объектов?

2024-05-13 14:12 UTC, tSpiny commented on 1-blog/styles/style.css
> +}
Центрирование, я так понимаю, будет затронуто дальше. О центрировании в лекциях пока вообще ничего не было

2024-05-13 14:14 UTC, tSpiny commented
> Всё окей в принципе, но можно оптимизировать, так же нужно ещё добавить "размеры блоков" и отцентровать. Примеры уже есть в комментариях.
> 
> а вот проект "2-form" не достилизован - над ним надо ещё поработать

По поводу недостилизован - задания его достилизовать не было, делаю строго в порядке как дано в курсе. По поводу центрирования - пока в курсе не было затронуто совсем. Полагаю, будет дальше

2024-05-13 14:16 UTC, tSpiny commented on 1-blog/styles/style.css
> +}
сделано

2024-05-14 07:37 UTC, GitEsense approved these changes
Всё отлично, ознакомьтесь с комментариями, учтите их на будущее и постараемся максимально переиспользовать всё что можно в рамках финальной работы с макетом блога и формы (при реализации flexbox)

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +}
> сделано

Можно ещё перенести font-size: 16px в body, т.к. он чаще всего встречается и ещё можно добавить
```css
* {
    box-sizing: border-box;
}
```
Чтобы сменить порядок расчёта размеров

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +    max-width: 1080px;
Чтобы не разрывать header 
![image](https://github.com/tSpiny/purpleschool-html-css/assets/101252030/b493a74a-1d2e-4738-b1dd-8ddc9083ccd1)

можно сделать следующим образом
```css
    margin: 0 auto;
    padding: 72px 0 69px;
```

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +}
Ну про "margin" речь шла ранее, так же это упоминалось в 12 разделе (5 урок), но вскользь, далее будет уже дополнительно "акцент", но можно было бы воспользоваться так же 
margin: 0 auto 20px;

тогда блок слева и справа получит "одинаковый отступ", а снизу 20px

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +    margin: 0 auto 30px auto;
Если у нас "лево и право" авто, то можно указать один раз (вторым параметром auto), ведь если сделать запись
```css
margin: 20px /* top = 20px, right = 20px, bottom = 20px, left = 20px */
margin: 20px 10px /* top = 20px, right = 10px, bottom = 20px, left = 10px */
margin: 20px 10px 5px /* top = 20px, right = 10px, bottom = 5px, left = 10px */
margin: 20px 15px 10px 5px /* top = 20px, right = 15px, bottom = 10px, left = 5px */
```
порядок чисел идёт:
`1 параметр` = `все`, 
`2 параметра` = `первое top + bottom, второе right + left`
`3 параметра` = `первое top,  второе right + left, третье bottom`
`4 параметра` = `первое top, второе right, третье bottom, 4 left`

Следовательно достаточно указать 
```css
margin: 0 auto 30px;
```

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +    text-align: center;
т.к. у нас параграф не ограничен по размеру, то по умолчанию блочный элемент занимает полностью всё свободное пространство, следовательно margin: 0 auto никак не влияет на происходящее, следовательно достаточно одного свойства text-align:center, чтобы текст был строго в центре блока

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +    font-size: 16px;
а вот про font-size чуть выше в блоке body оставил комментарий, тогда не будет необходимости указывать это у каждого селектора, что позволит "оптимизировать" код и наследовать его

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +}
Вот тут два свойства никак не повлияют на "происходящее", точнее одно будет лишним, второе не влияет, т.к. у нас ширина линии уже указана
```css
    vertical-align: middle; /* даёт ненужное смещение */
    height: 35px; /* line-height уже задаёт свой размер 35px */
```

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/index.html
> +      </div>
Вот эту запись можно упростить, сделав что-то вроде
```html
<a href="#" id="hero-link"><span id="logo">В</span>Мой блог</a>
```
Тогда у нас и иконка, и текст будут единой ссылкой

2024-05-14 07:37 UTC, GitEsense commented on 1-blog/styles/style.css
> +    text-align: center;
если данный параметр встречается у нескольких блоков в рамках одного родителя - можно указать его  у родителя, тогда дочерние будут наследовать положение текста

2024-05-14 07:37 UTC, GitEsense commented on 2-form/styles/style.css
> +    text-align: center;
text-align можно вынести на саму форму, тогда как и говорил ранее - все дочерние элементы их получат.  А потом уже у блока "лейбл + чекбокс" укажем отдельно переопределение "text-align: start"

2024-05-14 07:37 UTC, GitEsense commented on 2-form/styles/style.css
> +    font-weight: 400;
Точно так же можно вынести на отдельное определение и лишь для button указать "дополнительно", например
```css
body {
    /* тут какие-то параметры */
}
body, button {
    font-family: 'Open Sans', sans-serif;
    font-size: 18px;
    font-weight: 400;
}

2024-05-14 07:54 UTC, tSpiny commented on 1-blog/styles/style.css
> +    max-width: 1080px;
сделано

2024-05-14 07:54 UTC, tSpiny commented on 1-blog/styles/style.css
> +}
сделано

2024-05-14 07:55 UTC, tSpiny commented on 1-blog/styles/style.css
> +    margin: 0 auto 30px auto;
Для новичка явное лучше чем неявное) но сделаю так, окс

2024-05-14 07:55 UTC, tSpiny commented on 1-blog/styles/style.css
> +    text-align: center;
сделано понятно принято

2024-05-14 07:55 UTC, tSpiny commented on 1-blog/styles/style.css
> +}
исправлено

2024-05-14 07:59 UTC, tSpiny commented on 1-blog/styles/style.css
> +    text-align: center;
вынесено в main, для параграфов переписано в text-align: start

2024-05-14 08:01 UTC, tSpiny commented on 2-form/styles/style.css
> +    text-align: center;
вынесено в form

2024-05-14 08:24 UTC, tSpiny commented on 2-form/styles/style.css
> +    font-weight: 400;
Всё вынесла отдельно, кроме шрифта, он часто различается

2024-05-14 08:25 UTC, merged